export const FETCH_ALL_PRODUCT_BY_CATEGORY_ID =
  "FETCH_ALL_PRODUCT_BY_CATEGORY_ID";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT";
export const FETCH_PRODUCT_INFO = "FETCH_PRODUCT_INFO";
export const FETCH_ALL_PRODUCT_BY_PRODUCT_NAME = 'FETCH_ALL_PRODUCT_BY_PRODUCT_NAME';